.PHONY: raw gitlab turnup clean

raw:
	../probo --report -c probo.raw.conf

gitlab:
	../probo --report -c probo.gitlab.conf

turnup:
	../probo --report -c probo.turnup.conf

clean:
	rm -f *.txt *.svg *.png *.jpg *.jpeg *~

