#!/usr/bin/bash

function show-usage {
    echo "USAGE:"
    echo "    probo --init [-c CONF_FILE] REPORT_TYPE [GROUP...]"
    echo "    probo --ls"
    echo "    probo --log RUNFILE..."
    echo "    probo --addcase [COUNT]"
    echo "    probo --report [-c CONF_FILE]"
    echo "    probo --track [-d DESCRIPTION] STATUS RUNFILE..."
}

# 不定数のパラメータを取り、最初の存在するファイルを返す関数
function first-exist-file {
    for FILE in "$@"; do
        if [ -e "$FILE" ]; then
            echo "$FILE"
            return 0
        fi
    done    
    return 1
}

# 不定数のパラメータを取り、最初の空文字列でないものを返す関数
function choice-first-value {
    for ARG in "$@"; do
        if [ ! -z "$ARG" ]; then
            echo "$ARG"
            return 0
        fi
    done    
    return 1
}

# runfile 名の補完：４桁以下の数字列の場合のみ、カレントディレクトリにある test ID とみなす
function fix-runfile-name {
    if [[ "$1" =~ ^[0-9]{1,4}$ ]]; then
        local TMP="0000${1}"
        echo "${TMP: -4}.testrun.md"
    else
        echo "$1"
    fi
}

function generate-probo-schedule {

    local CURDATE="$PROBO_BD_STARTDAY"
    local ENDDATE="$PROBO_BD_ENDDAY"
    local UNIT="$PROBO_BD_EXEC_PER_DAY"
    local REST=$(find . -name '*.testcase.md' | wc -l)

    if [ -z "$CURDATE" ] || [ -z "$ENDDATE" ] || [ -z "$UNIT" ]; then
        return 1
    fi

    while :
    do
        if [ $REST -lt $UNIT ]; then
            echo "$CURDATE,$REST"
            REST=0
        else
            echo "$CURDATE,$UNIT"
            REST=$((REST - UNIT))
        fi
        if [ "$CURDATE" == "$ENDDATE" ]; then
            break
        fi
        CURDATE=$(date -d "$CURDATE + 1 day" +"%Y-%m-%d")
        if [ $? -ne 0 ]; then
            return 1
        fi
    done
}

function insert-data-to-markdown-file {
    local DAT_FILE="$1"
    local OUT_FILE="$2"
    local INS_MARK="$3"
    LINE1=$(cat "$OUT_FILE" | grep -n "<!-- begin $INS_MARK -->" | cut -d: -f1)
    LINE2=$(cat "$OUT_FILE" | grep -n "<!-- end $INS_MARK -->"   | cut -d: -f1)
    if [ -z "$LINE1" ] || [ -z "$LINE2" ]; then
        echo ""                         >> "$OUT_FILE"
        echo ""                         >> "$OUT_FILE"
        echo "<!-- begin $INS_MARK -->" >> "$OUT_FILE"
        cat  $DAT_FILE                  >> "$OUT_FILE"
        echo "<!-- end $INS_MARK -->"   >> "$OUT_FILE"
        echo ""                         >> "$OUT_FILE"
    else
        head    -$LINE1 $OUT_FILE >  $$.tmp
        cat             $DAT_FILE >> $$.tmp
        tail -n +$LINE2 $OUT_FILE >> $$.tmp
        rm -f "$OUT_FILE"
        mv $$.tmp "$OUT_FILE"
    fi
}

function generate-burndown-data-file-raw {
    local DAT_FILE="$1"
    local TODAY=$(date '+%Y-%m-%d')
    local REST1=$(find . -name '*.testcase.md' | wc -l)    # 基準線用残数
    local REST2=$REST1                                     # 実績用残数
    echo "日付	期待値	PASS数	FAIL数	基準線	実績" > "${DAT_FILE}"
    for LINE in ${PROBO_BD_SCHEDULE}
    do
        local DATE=$(echo      "$LINE" | cut -d , -f 1)
        local ESTIMATED=$(echo "$LINE" | cut -d , -f 2)
        local COUNT=""
        local NGCNT=""
        REST1=$((REST1 - ESTIMATED))
        if [ "$TODAY" "<" "$DATE" ]; then
            REST2=""
        else
            COUNT=$(find . -name '*.testrun.md' | xargs grep "## ${DATE}-.*\.PASS" | wc -l)
            NGCNT=$(find . -name '*.testrun.md' | xargs grep "## ${DATE}-.*\.FAIL" | wc -l)
            REST2=$((REST2 - COUNT))
        fi
        echo "${DATE}	${ESTIMATED}	${COUNT}	${NGCNT}	${REST1}	${REST2}" >> "${DAT_FILE}"
    done
}

function generate-summary-data-file-raw {
    local OUT_FILE="$1"
    TOTALS=(0 0 0 0 0 0 0)        # READY,BLOCK,RUN,OTHER,FAIL,PASS,TOTAL
    echo "GROUP	READY	BLOCK	RUN	OTHER	FAIL	PASS	TOTAL	PROGRESS" > "${OUT_FILE}"
    for GROUP in ${PROBO_GROUPS}
    do
        pushd ${GROUP} > /dev/null
        COUNTS=(0 0 0 0 0 0 0)    # READY,BLOCK,RUN,OTHER,FAIL,PASS,TOTAL
        for RUN_FILE in $(ls *.testrun.md)
        do
            RESULT=$(grep '^## ....-..-..-' ${RUN_FILE} | tail -1 | cut -d. -f2)
            case "${RESULT}" in
                READY ) COUNTS[0]=$((COUNTS[0] + 1));;
                BLOCK ) COUNTS[1]=$((COUNTS[1] + 1));;
                RUN )   COUNTS[2]=$((COUNTS[2] + 1));;
                FAIL )  COUNTS[4]=$((COUNTS[4] + 1));;
                PASS )  COUNTS[5]=$((COUNTS[5] + 1));;
                * )     COUNTS[3]=$((COUNTS[3] + 1));;
            esac
            COUNTS[6]=$((COUNTS[6] + 1))
        done
        local PROGRESS=$(ins-pt $((COUNTS[5] * 1000 / COUNTS[6])))
        echo "${GROUP}	${COUNTS[0]}	${COUNTS[1]}	${COUNTS[2]}	${COUNTS[3]}	${COUNTS[4]}	${COUNTS[5]}	${COUNTS[6]}	${PROGRESS}%" >> ../"${OUT_FILE}"
        for ((i=0; i<7; i++)) do
            TOTALS[i]=$((TOTALS[i] + COUNTS[i]))
        done
        popd > /dev/null
    done
    local PROGRESS=$(ins-pt $((TOTALS[5] * 1000 / TOTALS[6])))
    echo "(total)	${TOTALS[0]}	${TOTALS[1]}	${TOTALS[2]}	${TOTALS[3]}	${TOTALS[4]}	${TOTALS[5]}	${TOTALS[6]}	${PROGRESS}%" >> ./"${OUT_FILE}"
}

function generate-summary-data-file-markdown {
    local OUT_FILE="$1"
    local INS_FLAG="$2"
    # 最初に一時ファイルとして raw 形式ファイルを作成
    generate-summary-data-file-raw "$$.summary.raw.tmp"

    # ヘッダ行は raw file を無視して固定で出しちゃう
    echo "| GROUP | READY | BLOCK | RUN | OTHER | FAIL | PASS | TOTAL | PROGRESS |"  > "$$.summary.tmp"
    echo "|:------|------:|------:|----:|------:|-----:|-----:|------:|---------:|" >> "$$.summary.tmp"

    # ２行目以降は markdown の表形式に変換（INS_FLAG に応じて分岐）
    tail -n +2 "$$.summary.raw.tmp" | perl -pe 's/	/ | /g' \
                                    | perl -pe 's/^/| /'  \
                                    | perl -pe 's/$/ |/'       >> "$$.summary.tmp"
    rm -f "$$.summary.raw.tmp"
    # INS_FLAG の値で分岐
    if [ "$INS_FLAG" -eq 1 ]; then
        # 1 なら差し込みを実施
        insert-data-to-markdown-file "$$.summary.tmp" "$OUT_FILE" "probo summary"
        rm -f "$$.summary.tmp"
    else
        # 1 以外なら単純にリネーム
        mv "$$.summary.tmp" "$OUT_FILE"
    fi
}


function generate-status-file-raw {
	local OUT_FILE="$1"
    echo "GROUP	CASE	TIMESTAMP	STATUS	DESRIPTION" > $OUT_FILE
    for GROUP in ${PROBO_GROUPS}
    do
        pushd ${GROUP} > /dev/null
        for RUN_FILE in $(ls *.testrun.md)
        do
            NUMBER=$(echo "$RUN_FILE" | cut -d. -f1)
            TAIL=$(grep '^## ....-..-..-' ${RUN_FILE} | tail -1)
            TIMESTAMP=$(echo ${TAIL:3} | cut -d. -f1 | perl -pe 's@^(....)-(..)-(..)-(..)-(..)@\1/\2/\3 \4:\5@')
            STATUS=$(echo ${TAIL} | cut -d. -f2)
            DESCRIPTION=$(echo ${TAIL} | cut -d. -f3)
            echo "${GROUP}	${NUMBER}	${TIMESTAMP}	${STATUS}	${DESCRIPTION}" >> ../$OUT_FILE
        done
        popd > /dev/null
    done
}

function generate-status-file-markdown {
    local FILE_MODE="$1"    # full or pickup
    local RAW_TMPFILE="$2"
    local OUT_FILE="$3"
    local INS_FLAG="$4"

    # ヘッダ行は raw file を無視して固定で出しちゃう
    echo "| GROUP | CASE | TIMESTAMP | STATUS | DESRIPTION |"  >  "$$.status.tmp"
    echo "|:------|:----:|:---------:|:------:|:-----------|" >>  "$$.status.tmp"

    # ２行目以降は markdown の表形式に変換（FILE_MODE に応じて分岐）
    if [ "$FILE_MODE" == "pickup" ]; then
        tail -n +2 "$RAW_TMPFILE" | grep -v '	PASS	' \
                                  | grep -v '	READY	' \
                                  | perl -pe 's/	/ | /g' \
                                  | perl -pe 's/^/| /'  \
                                  | perl -pe 's/$/ |/'       >>  "$$.status.tmp"
    else
        tail -n +2 "$RAW_TMPFILE" | perl -pe 's/	/ | /g' \
                                  | perl -pe 's/^/| /'  \
                                  | perl -pe 's/$/ |/'       >>  "$$.status.tmp"
    fi
    # INS_FLAG の値で分岐
    if [ "$INS_FLAG" -eq 1 ]; then
        # 1 なら差し込みを実施
        insert-data-to-markdown-file "$$.status.tmp" "$OUT_FILE" "probo status-${FILE_MODE}"
        rm -f "$$.status.tmp"
    else
        # 1 以外なら単純にリネーム
        mv "$$.status.tmp" "$OUT_FILE"
    fi
}

function get-image-type-from-filename {
    local IMG_TYPE="${1##*.}"    # 最後のピリオドまでを削除
    case "$IMG_TYPE" in
        svg )   ;;
        png )   ;;
        gif )   ;;
        jpeg )  ;;
        jpg )   IMG_TYPE="jpeg";;
        * )     IMG_TYPE="";;
    esac
    echo "$IMG_TYPE"
}

function make-burndown-gpfile {
    local OUT_FILE="$1"
    local DAT_FILE="$2"
    local IMG_TYPE="$3"    # svg|png|jpeg|gif
    local TOP_Y1="$4"
    local TOP_Y2="$5"
    local IMG_W=$(choice-first-value "$PROBO_BDIMG_WIDTH"  "800")
    local IMG_H=$(choice-first-value "$PROBO_BDIMG_HEIGHT" "400")
    local BGCLR=$(choice-first-value "$PROBO_BDIMG_BGCLR"    "white")
    local CLR1=$(choice-first-value "$PROBO_BDIMG_CLR_GUIDE"    "gray")
    local CLR2=$(choice-first-value "$PROBO_BDIMG_CLR_PASSLINE" "blue")
    local CLR3=$(choice-first-value "$PROBO_BDIMG_CLR_FAILBOX"   "red")
    local IMG_SIZE="$IMG_W,$IMG_H"

    if [ "$IMG_TYPE" == "svg" ]; then
        echo "set terminal ${IMG_TYPE} size ${IMG_SIZE} fixed background rgb \"${PROBO_BDIMG_BGCLR}\"" > ${OUT_FILE}
    else
        echo "set terminal ${IMG_TYPE} size ${IMG_SIZE} background rgb \"${PROBO_BDIMG_BGCLR}\"" > ${OUT_FILE}
    fi
    
    cat >> "${OUT_FILE}" <<EOF
set datafile separator ","

# x軸が日付データであることを宣言
set xdata time
# 入力データの書式（例: 年/月/日）
set timefmt "%Y-%m-%d"
# グラフ軸の表示書式（例: 月/日）
set format x "%m/%d"

set yrange [0:${TOP_Y1}]

# 第2軸（y2軸）のメモリを表示するように設定
set ytics nomirror
set y2tics
set grid
set y2range [0:${TOP_Y2}]

# 棒グラフの幅を調整（任意）
set boxwidth 0.2 relative
set style fill solid 0.75

# 描画の実行
plot "${DAT_FILE}" using 1:2 with linespoints pt 5 ps 0.5 linecolor rgb "$CLR1" title "GuideLine", \\
     "${DAT_FILE}" using 1:3 with linespoints pt 7 ps 0.5 linecolor rgb "$CLR2" title "Pass", \\
     "${DAT_FILE}" using 1:4 with boxes       axes x1y2   linecolor rgb "$CLR3" title "Fail"
EOF
}

function make-burndown-image {
    local DAT_FILE="$1"
    local OUT_FILE="$2"
    local IMG_TYPE="$3"
    # DAT_FILE を走査して TOP_Y1/TOP_Y2 を割り出す
    local TOP_Y1=$(cat $DAT_FILE | cut -d, -f2 | sort -g | tail -1)    # line graph
    local TOP_Y2=$(cat $DAT_FILE | cut -d, -f4 | sort -g | tail -1)    # Fail
    TOP_Y1=$((TOP_Y1 + 10))
    TOP_Y2=$((TOP_Y2 * 10))
    # gnuplot 設定ファイルを作成
    make-burndown-gpfile "$$.tmp.gp" "$DAT_FILE" ${IMG_TYPE} $TOP_Y1 $TOP_Y2
    gnuplot "$$.tmp.gp" > "${OUT_FILE}"
    rm -f "$$.tmp.gp"
}

function make-summary-gpfile {
    local OUT_FILE="$1"
    local DAT_FILE="$2"
    local IMG_TYPE="$3"    # svg|png|jpeg|gif
    local IMG_W=$(choice-first-value "$PROBO_SUMIMG_WIDTH"  "500")
    local IMG_H=$(choice-first-value "$PROBO_SUMIMG_HEIGHT" "400")
    local BGCLR=$(choice-first-value "$PROBO_SUMIMG_BGCLR"      "white")
    local CLR1=$(choice-first-value "$PROBO_SUMIMG_CLR_READY"    "gray")
    local CLR2=$(choice-first-value "$PROBO_SUMIMG_CLR_BLOCK"  "purple")
    local CLR3=$(choice-first-value "$PROBO_SUMIMG_CLR_OTHER" "#98FB98")
    local CLR4=$(choice-first-value "$PROBO_SUMIMG_CLR_FAIL"     "pink")
    local CLR5=$(choice-first-value "$PROBO_SUMIMG_CLR_RUN"      "blue")
    local CLR6=$(choice-first-value "$PROBO_SUMIMG_CLR_PASS"     "cyan")
    local IMG_SIZE="$IMG_W,$IMG_H"

    if [ "$IMG_TYPE" == "svg" ]; then
        echo "set terminal ${IMG_TYPE} size ${IMG_SIZE} fixed background rgb \"${PROBO_SUMIMG_BGCLR}\"" > ${OUT_FILE}
    else
        echo "set terminal ${IMG_TYPE} size ${IMG_SIZE} background rgb \"${PROBO_SUMIMG_BGCLR}\"" > ${OUT_FILE}
    fi
    
    cat >> "${OUT_FILE}" <<EOF
set datafile separator ","

# 角度を「度」に設定
set angles degrees

# グラフを正方形にする（円が楕円にならないようにする）
set size ratio -1

# 塗りつぶしの設定
set style fill solid 1.0 border lt -1
#set style fill solid 1.0 noborder

# 軸や目盛りを非表示にする（任意）
unset tics
unset border

# ラベルを表示する位置の半径（外半径が1の場合、0.7くらいが適当）
r_label = 0.7

set lt 1 lc rgb "$CLR1"
set lt 2 lc rgb "$CLR2"
set lt 3 lc rgb "$CLR3"
set lt 4 lc rgb "$CLR4"
set lt 5 lc rgb "$CLR5"
set lt 6 lc rgb "$CLR6"

set yrange [-1.1:1.1]
set xrange [-1.1:1.1]  # x軸も同様に広げるとバランスが良くなります

# 画像の右下（完全に端）に配置
set key outside bottom right

# 描画の実行
# using 1:2:3:4:5:6 は (x:y:radius:begin:end:color) に対応
plot "${DAT_FILE}" using 1:2:3:4:5:6 with circles lc variable notitle, \\
     keyentry with boxes lt 1 title "READY", \\
     keyentry with boxes lt 2 title "BLOCK", \\
     keyentry with boxes lt 3 title "OTHER", \\
     keyentry with boxes lt 4 title "FAIL", \\
     keyentry with boxes lt 5 title "RUN", \\
     keyentry with boxes lt 6 title "PASS", \\
     "${DAT_FILE}" using \\
     (\$1 + r_label * cos((\$4+\$5)/2.0)) : \\
     (\$2 + r_label * sin((\$4+\$5)/2.0)) : \\
     (stringcolumn(7)) with labels center font ",12" tc rgb "black" notitle
EOF
}

function ins-pt {
    local NUM="$1"
    if [ "${#NUM}" -eq 1 ]; then
        echo "0.$NUM"
    else
        echo "${NUM%?}.${NUM#${NUM%?}}"
    fi
}

function make-summary-image {
    local OUT_FILE="$1"
    local IMG_TYPE="$2"
    local CASES=("$3" "$4" "$5" "$6" "$7" "$8") # READY,BLOCK,OTHER,FAIL,RUN,PASS

    local N_TOTAL=$((CASES[0] + CASES[1] + CASES[2] + CASES[3] + CASES[4] + CASES[5]))
    local DEG1=0

    echo "# 中心X  中心Y  半径  開始角  終了角  色番号  表示する値" >  "$$.tmp.dat"
    for ((i=0; i<6; i++)) do
        local DEGREE=$((CASES[i] * 3600 / N_TOTAL))
        if [ "${CASES[i]}" -ne 0 ]; then
            local DEG2=$((DEG1 + DEGREE))
            echo "0,0,1,$(ins-pt ${DEG1}),$(ins-pt ${DEG2}),$((i + 1)),${CASES[i]}" >> "$$.tmp.dat"
            DEG1=${DEG2}
        fi
    done

    # gnuplot 設定ファイルを作成
    make-summary-gpfile "$$.tmp.gp" "$$.tmp.dat" ${IMG_TYPE}
    gnuplot "$$.tmp.gp" > "${OUT_FILE}"
    rm -f "$$.tmp.gp"
    rm -f "$$.tmp.dat"
}

function graph-summary {
    local OUT_FILE="$1"
    COUNTS=(0 0 0 0 0 0)    # READY,BLOCK,FAIL,RUN,PASS,OTHER
    for GROUP in ${PROBO_GROUPS}
    do
        pushd ${GROUP} > /dev/null
        for RUN_FILE in $(ls *.testrun.md)
        do
            RESULT=$(grep '^## ....-..-..-' ${RUN_FILE} | tail -1 | cut -d. -f2)
            case "${RESULT}" in
                READY ) COUNTS[0]=$((COUNTS[0] + 1));;
                BLOCK ) COUNTS[1]=$((COUNTS[1] + 1));;
                FAIL )  COUNTS[2]=$((COUNTS[2] + 1));;
                RUN )   COUNTS[3]=$((COUNTS[3] + 1));;
                PASS )  COUNTS[4]=$((COUNTS[4] + 1));;
                * )     COUNTS[5]=$((COUNTS[5] + 1));;
            esac
        done
        popd > /dev/null
    done
    IMG_TYPE=$(get-image-type-from-filename "$OUT_FILE")
    make-summary-image "$OUT_FILE" $IMG_TYPE \
                       ${COUNTS[0]} ${COUNTS[1]} ${COUNTS[5]} ${COUNTS[2]} ${COUNTS[3]} ${COUNTS[4]}
    rm -f ${DAT_FILE}
}

function graph-burndown {
    # ToDo : generate-burndown-data-file-raw を利用するかたちにできそう
    local IMG_FILE="$1"
    local DAT_FILE="$$.burndown.dat"
    local TODAY=$(date '+%Y-%m-%d')
    local REST1=$(find . -name '*.testcase.md' | wc -l)    # 基準線用残数
    local REST2=$REST1                                     # 実績用残数
    for LINE in ${PROBO_BD_SCHEDULE}
    do
        local DATE=$(echo      "$LINE" | cut -d , -f 1)
        local ESTIMATED=$(echo "$LINE" | cut -d , -f 2)
        local COUNT=""
        local NGCNT=""
        REST1=$((REST1 - ESTIMATED))
        if [ "$TODAY" "<" "$DATE" ]; then
            REST2=""
        else
            COUNT=$(find . -name '*.testrun.md' | xargs grep "## ${DATE}-.*\.PASS" | wc -l)
            NGCNT=$(find . -name '*.testrun.md' | xargs grep "## ${DATE}-.*\.FAIL" | wc -l)
            REST2=$((REST2 - COUNT))
        fi
        echo "${DATE},${REST1},${REST2},${NGCNT}" >> ${DAT_FILE}
    done
    IMG_TYPE=$(get-image-type-from-filename "$IMG_FILE")
    make-burndown-image "$DAT_FILE" "$IMG_FILE" $IMG_TYPE
    rm -f ${DAT_FILE}
}

function track-runfile-impl {
    TIMESTAMP="$1"
    STATUS="$2"
    DESCRIPTION="$3"
    COMMENT="$4"
    echo ""                                        >> "$RUN_FILE"
    echo "## ${TIMESTAMP}.${STATUS}${DESCRIPTION}" >> "$RUN_FILE"
    echo ""                                        >> "$RUN_FILE"
    if [ "$COMMENT" -eq 1 ]; then
        echo "<!-- Add info here. -->"             >> "$RUN_FILE"
        echo ""                                    >> "$RUN_FILE"
    fi
}

function track-runfile {

    # -f / -d オプションの回収（あれば）
    local FORCE=0
    local DESCRIPTION=""
    while getopts "d:f" opt; do
        case $opt in
            d) DESCRIPTION="${OPTARG}" ;;
            f) FORCE=1 ;;
            *) echo "ERROR : invalid option."
               return 1;;
        esac
    done
    shift $((OPTIND - 1))

    # STATUS パラメータの回収とチェック（ただし -f オプションありの場合チェックはバイパス）
    local STATUS="${1^^}"
    shift
    if [ $FORCE -eq 0 ]; then
        case $STATUS in
            READY) ;;
            BLOCK) ;;
            PASS)  ;;
            FAIL)  ;;
            RUN)   ;;
            *) echo "ERROR : invalid status \"$STATUS\"."
               return 1;;
        esac
    fi
    # 追加する行の生成
    if [ ! -z "$DESCRIPTION" ]; then
        DESCRIPTION=".$DESCRIPTION"
    fi
    local TIMESTAMP=$(date '+%Y-%m-%d-%H-%M')
    local NEW_LINE="## ${TIMESTAMP}.${STATUS}${DESCRIPTION}"

    # 対象ファイルの反復と処理
    local FILE_COUNT=0
    for RUN_FILE in $@
    do
        RUN_FILE=$(fix-runfile-name "$RUN_FILE")
        if [ ! -e "$RUN_FILE" ]; then
            echo "ERROR : runfile $RUN_FILE is not found."
        else
            track-runfile-impl "${TIMESTAMP}" "${STATUS}" "${DESCRIPTION}" 1
            FILE_COUNT=$((FILE_COUNT + 1))
        fi
    done
    echo "$FILE_COUNT file(s) updated."
}

function load-conf-file {
    local CONF_FILE="$1"

    # カレントディレクトリに conf file がなければエラー終了
    if [ ! -e "$CONF_FILE" ]; then
        echo "ERROR : $CONF_FILE missing."
        return 1
    fi

    source "$CONF_FILE"

    # PROBO_GROUPS が空ならディレクトリを走査して生成
    if [ -z "$PROBO_GROUPS" ]; then
        PROBO_GROUPS=$(find . -maxdepth 1 -type d | grep -v '^\.$' | cut -d/ -f2 | grep -v '^\.' | sort)
    fi
    # PROBO_BD_SCHEDULE が空なら生成
    if [ -z "${PROBO_BD_SCHEDULE}" ]; then
        PROBO_BD_SCHEDULE=$(generate-probo-schedule)
        if [ $? -ne 0 ]; then
            echo "ERROR : Schedule generation failed."
            return 1
        fi
    fi
    # PROBO_REPORT_TYPE の正当性チェック
    case "${PROBO_REPORT_TYPE}" in
        raw)      ;;
        markdown) ;;
        *) echo "ERROR : invalid PROBO_REPORT_TYPE variable."
           return 1;;
    esac

    return 0
}

function generate-probo-conf-file {
    local CONF_FILE="$1"
    local REPORT_TYPE="$2"
    local GNUPLOT_FLAG="$3"

    local FULLSTAT_FILE=""
    local PARTSTAT_FILE=""
    local BDDAT_FILE=""
    local SUMDAT_FILE=""
    local BDIMG_FILE=""
    local SUMIMG_FILE=""
    local DAY1=$(date -d "$(date +%Y-%m-01) +1 month"         +%Y-%m-%d)    # 翌月の初日
    local DAY2=$(date -d "$(date +%Y-%m-01) +2 month -1 days" +%Y-%m-%d)    # 翌月の末日

    if [ "$REPORT_TYPE" == "raw" ]; then
        FULLSTAT_FILE="full_stat.txt"
        PARTSTAT_FILE="part_stat.txt"
        BDDAT_FILE="burndown_data.txt"
        SUMDAT_FILE="summary.txt"
    else
        FULLSTAT_FILE="full_stat.md"
        PARTSTAT_FILE="part_stat.md"
        BDDAT_FILE=""
        SUMDAT_FILE="summary.md"
    fi
    if [ $GNUPLOT_FLAG -eq 1 ]; then
        BDIMG_FILE="burndown.svg"
        SUMIMG_FILE="summary.svg"
    fi

    cat <<EOF > "$CONF_FILE"
PROBO_REPORT_TYPE="$REPORT_TYPE"

PROBO_FULLSTAT_FILENAME="$FULLSTAT_FILE"
PROBO_FULLSTAT_INSERTION=0

PROBO_PARTSTAT_FILENAME="$PARTSTAT_FILE"
PROBO_PARTSTAT_INSERTION=0

PROBO_BDDAT_FILENAME="$BDDAT_FILE"

PROBO_SUMDAT_FILENAME="$SUMDAT_FILE"
PROBO_SUMDAT_INSERTION=0

PROBO_BDIMG_FILENAME="$BDIMG_FILE"
PROBO_BDIMG_WIDTH=
PROBO_BDIMG_HEIGHT=
PROBO_BDIMG_BGCLR=
PROBO_BDIMG_CLR_GUIDE=
PROBO_BDIMG_CLR_PASSLINE=
PROBO_BDIMG_CLR_FAILBOX=

PROBO_SUMIMG_FILENAME="$SUMIMG_FILE"
PROBO_SUMIMG_WIDTH=
PROBO_SUMIMG_HEIGHT=
PROBO_SUMIMG_BGCLR=
PROBO_SUMIMG_CLR_READY=
PROBO_SUMIMG_CLR_BLOCK=
PROBO_SUMIMG_CLR_RUN=
PROBO_SUMIMG_CLR_PASS=
PROBO_SUMIMG_CLR_FAIL=
PROBO_SUMIMG_CLR_OTHER=

PROBO_GROUPS=

PROBO_BD_STARTDAY="$DAY1"
PROBO_BD_ENDDAY="$DAY2"
PROBO_BD_EXEC_PER_DAY=5

PROBO_BD_SCHEDULE=
EOF
}

function initialize-probo {

    # -c オプションの回収（あれば）
    local CONF_FILE="probo.conf"
    while getopts "c:" opt; do
        case $opt in
            c) CONF_FILE="${OPTARG}" ;;
            *) echo "ERROR : invalid option."
               return 1;;
        esac
    done
    shift $((OPTIND - 1))

    # カレントディレクトリに指定 conf file がすでにあればエラー
    if [ -e "$CONF_FILE" ]; then
        echo "ERROR : $CONF_FILE has already exists."
        exit 1
    fi

    local REPORT_TYPE="$1"
    # REPORT_TYPE の正当性チェック
    case "${REPORT_TYPE}" in
        raw)      ;;
        markdown) ;;
        *) echo "ERROR : invalid REPORT_TYPE parameter."
           return 1;;
    esac
    shift 1

    generate-probo-conf-file "$CONF_FILE" "$REPORT_TYPE" $(which gnuplot | wc -l)

    local GROUP_NAME="$1"
    while [ ! -z "$GROUP_NAME" ]; do
        if [ ! -d "$GROUP_NAME" ]; then
            mkdir "./$GROUP_NAME"
        fi
        shift 1
        GROUP_NAME="$1"
    done
    
}

function add-test-case-impl {
    local ID="0000${1}"
    local GROUP="$2"
    local TIMESTAMP="$3"
    local CASE_TMPL="$4"
    ID="${ID: -4}"
    CASE_FILE="$ID.testcase.md"
    RUN_FILE="$ID.testrun.md"
    echo "Adding test case $ID..."
    if [ -z "$CASE_TMPL" ]; then
        touch "$CASE_FILE"
    else
        cat "$CASE_TMPL" | perl -pe "s/%CASEID%/${ID}/g"   \
                         | perl -pe "s/%GROUP%/${GROUP}/g" > "$CASE_FILE"
    fi   
    track-runfile-impl "$TIMESTAMP" "NEW" "" 0
}

function add-test-case {
    local COUNT="$1"
    if [ -z "$COUNT" ]; then
        COUNT=1
    fi
    if [[ ! "$COUNT" =~ ^[1-9][0-9]*$ ]]; then
        echo "ERROR : invalid parameter \"$COUNT\"."
        return 1
    fi
    local CASE_TMPL=$(first-exist-file "./.case.template" "../.case.template")
    local GROUP=$(basename $(pwd))
    local TIMESTAMP=$(date '+%Y-%m-%d-%H-%M')
    local CURTAIL=0
    if [ $(ls *.testcase.md 2> /dev/null | wc -l) -ne 0 ]; then
        CURTAIL=$(ls *.testcase.md | sort | tail -1 | cut -d. -f1)
    fi
    local COUNT=$((10#$COUNT))
    CURTAIL=$((10#$CURTAIL))
    for ((i=0; i<$COUNT; i++)) do
        add-test-case-impl $((CURTAIL + 1 + i)) "$GROUP" "$TIMESTAMP" "$CASE_TMPL"
    done
}

function dump-runfile-log {
    for RUN_FILE in $@
    do
        RUN_FILE=$(fix-runfile-name "$RUN_FILE")
        if [ ! -e "$RUN_FILE" ]; then
            echo "ERROR : runfile $RUN_FILE is not found."
        else
            TEST_ID=$(echo "$RUN_FILE" | perl -pe 's/^(.+?)\.testrun\.md$/\1/')
            while IFS= read -r LINE; do
                TIMESTAMP=$(  echo "${LINE:3}" | cut -d. -f1)
                STATUS=$(     echo "${LINE:3}" | cut -d. -f2)
                DESCRIPTION=$(echo "${LINE:3}" | cut -d. -f3)
                echo "${TEST_ID}	${TIMESTAMP}	${STATUS}	${DESCRIPTION}"
            done < <(grep -E '^## ....-..-..-..-..\..+' "$RUN_FILE" )
        fi
    done
}

function dump-current-group-status {
    echo "CASE	TIMESTAMP	STATUS	DESRIPTION"
    for RUN_FILE in $(ls *.testrun.md)
    do
        NUMBER=$(echo "$RUN_FILE" | cut -d. -f1)
        TAIL=$(grep '^## ....-..-..-' ${RUN_FILE} | tail -1)
        TIMESTAMP=$(echo ${TAIL:3} | cut -d. -f1 | perl -pe 's@^(....)-(..)-(..)-(..)-(..)@\1/\2/\3 \4:\5@')
        STATUS=$(     echo ${TAIL} | cut -d. -f2)
        DESCRIPTION=$(echo ${TAIL} | cut -d. -f3)
        echo "${NUMBER}	${TIMESTAMP}	${STATUS}	${DESCRIPTION}"
    done
}

function generate-report-files-raw {

    # status file 指定があれば生成（raw target では insertion 指定は無視）
    if [ ! -z "${PROBO_FULLSTAT_FILENAME}" ] || [ ! -z "${PROBO_PARTSTAT_FILENAME}" ]; then
        # 最初に一時ファイルとして作成
        generate-status-file-raw "$$.status.tmp"
        # pickup ファイルが指定されていれば grep -v chain で作成
        if [ ! -z "${PROBO_PARTSTAT_FILENAME}" ]; then
            cat "$$.status.tmp" | grep -v '	PASS	' \
                                | grep -v '	READY	' >  "${PROBO_PARTSTAT_FILENAME}"
        fi
        # full ファイルが指定されていれば mv で一時ファイルを rename
        if [ ! -z "${PROBO_FULLSTAT_FILENAME}" ]; then
            mv "$$.status.tmp" "${PROBO_FULLSTAT_FILENAME}"
        else
            # 指定なしなら一時ファイルを削除
            rm -f "$$.status.tmp"
        fi
    fi
    # burn-down data file 指定があれば生成
    if [ ! -z "${PROBO_BDDAT_FILENAME}" ]; then
        generate-burndown-data-file-raw "${PROBO_BDDAT_FILENAME}"
    fi
    # summary data file 指定があれば生成（raw target では insertion 指定は無視）
    if [ ! -z "${PROBO_SUMDAT_FILENAME}" ]; then
        generate-summary-data-file-raw "${PROBO_SUMDAT_FILENAME}"
    fi
	# ファイル名が指定されている場合のみグラフ生成
    if [ ! -z "$PROBO_BDIMG_FILENAME" ]; then
        graph-burndown "$PROBO_BDIMG_FILENAME"
    fi
    if [ ! -z "$PROBO_SUMIMG_FILENAME" ]; then
        graph-summary "$PROBO_SUMIMG_FILENAME"
    fi

	return 0
}

function generate-report-files-markdown {

    # status file 指定があれば生成
    if [ ! -z "${PROBO_FULLSTAT_FILENAME}" ] || [ ! -z "${PROBO_PARTSTAT_FILENAME}" ]; then
        # 最初に一時ファイルとして raw 形式ファイルを作成
        generate-status-file-raw "$$.status.raw.tmp"
        # pickup ファイルが指定されていれば作成
        if [ ! -z "${PROBO_PARTSTAT_FILENAME}" ]; then
            generate-status-file-markdown 'pickup' "$$.status.raw.tmp" \
                                          "$PROBO_PARTSTAT_FILENAME" "$PROBO_PARTSTAT_INSERTION"
        fi
        # full ファイルが指定されている場合
        if [ ! -z "${PROBO_FULLSTAT_FILENAME}" ]; then
            generate-status-file-markdown 'full' "$$.status.raw.tmp" \
                                          "$PROBO_FULLSTAT_FILENAME" "$PROBO_FULLSTAT_INSERTION"
        fi
        # 一時ファイルを削除
        rm -f "$$.status.raw.tmp"
    fi
    # burn-down data file 指定があれば生成
    if [ ! -z "${PROBO_BDDAT_FILENAME}" ]; then
        generate-burndown-data-file-raw "${PROBO_BDDAT_FILENAME}"
    fi
    # summary data file 指定があれば生成
    if [ ! -z "${PROBO_SUMDAT_FILENAME}" ]; then
        generate-summary-data-file-markdown "$PROBO_SUMDAT_FILENAME" "$PROBO_SUMDAT_INSERTION"
    fi
	# ファイル名が指定されている場合のみグラフ生成
    if [ ! -z "$PROBO_BDIMG_FILENAME" ]; then
        graph-burndown "$PROBO_BDIMG_FILENAME"
    fi
    if [ ! -z "$PROBO_SUMIMG_FILENAME" ]; then
        graph-summary "$PROBO_SUMIMG_FILENAME"
    fi

	return 0
}

function generate-reports {

    CONF_FILE="./probo.conf"

    # -c オプションの回収（あれば）
    while getopts "c:" opt; do
        case $opt in
            c) CONF_FILE="${OPTARG}" ;;
            *) echo "ERROR : invalid option."
               return 1;;
        esac
    done
    shift $((OPTIND - 1))

    # loading conf file 
    load-conf-file "$CONF_FILE"
    if [ $? -ne 0 ]; then
        return 1
    fi

    if [ "$MODE" == "--report" ]; then

        # gnuplot 要否、および存在チェック
        if [ ! -z "$PROBO_BDIMG_FILENAME" ] || [ ! -z "$PROBO_SUMIMG_FILENAME" ]; then
            if [ $(which gnuplot | wc -l) -eq 0 ]; then
                echo "ERROR : gnuplot is missing."
                return 1
            fi
        fi
        generate-report-files-${PROBO_REPORT_TYPE}
    fi

}

MODE="$1"
shift

# モード指定がなければ show-usage して終わり
if [ -z "$MODE" ]; then
    show-usage
    exit 1
fi

# モード指定で分岐
case "$MODE" in
    --help )    show-usage
                exit 0;;
    --init )    initialize-probo "$@"
                exit 0;;
    --ls )      dump-current-group-status
                exit 0;;
    --log )     dump-runfile-log "$@"
                exit 0;;
    --track )   track-runfile "$@"
                exit 0;;
    --addcase ) add-test-case "$@"
                exit 0;;
    --report )  generate-reports "$@"
                exit 0;;
    * )         echo "ERROR: Invalid option \"$MODE\"."
                echo ""
                show-usage
                exit 1;;
esac

